name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/switch-stuffs-dependencies:latest

    steps:
      - name: Checkout nxcfw
        uses: actions/checkout@v4
        with:
          repository: laleeroy/nxcfw
          path: configs

      - name: Checkout switch-logo-patcher
        uses: actions/checkout@v4
        with:
          repository: friedkeenan/switch-logo-patcher
          path: switch-logo-patcher

      - name: Checkout atmosphere
        uses: actions/checkout@v4
        with:
          repository: laleeroy/Atmosphere-
          path: ams
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Install Dependencies
        run: |
          pip3 install -r switch-logo-patcher/requirements.txt

      - name: Generate BL Patches
        run: |
          python3 switch-logo-patcher/gen_patches.py configs/atmosphere/exefs_patches/bl_patches configs/logo/8bg.png

      - name: Build
        run: |
          make -C ams -f atmosphere.mk dist-no-debug -j$(nproc)
          unzip ams/out/nintendo_nx_arm64_armv8a/release/atmosphere*.zip -d configs

      - name: Compile
        run: |
          cd configs
          bash update.sh
          rm -rf update.sh Dockerfile requirements.txt logo .git*

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: 8BP-Unknown
          path: configs/
          include-hidden-files: true
