name: Test

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag name for the release (e.g., v1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
      - name: Checkout configs
        uses: actions/checkout@v4
        with:
          repository: laleeroy/nxcfw
          path: configs
          ref: configs

      - name: Checkout switch-logo-patcher
        uses: actions/checkout@v4
        with:
          repository: friedkeenan/switch-logo-patcher
          path: switch-logo-patcher
          ref: master

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3 python3-pip

      - name: Install Python requirements for switch-logo-patcher
        run: |
          # Navigate into the checked-out repository
          cd switch-logo-patcher
          # Install dependencies from requirements.txt
          pip3 install -r requirements.txt

