name: Build Docker Image

on:
  workflow_dispatch:
    branches:
      - main
    paths:
      - 'Dockerfile'

env:
  IMAGE_NAME: switch-stuffs-dependencies

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: |
          docker build . --no-cache \
          --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${{ github.run_id }}"
      - name: Log in to registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Push Image
        run: |
          docker tag $IMAGE_NAME ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
          docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
